import SpWorker from '../../models/SpWorker.js';
import { generateOTP, hashOTP, storeOTP, verifyOTP, checkRateLimit } from '../../services/redisOtp.util.js';
import { generateTokenPair, verifyRefreshToken, generateVerificationToken, verifyVerificationToken } from '../../services/tokenService.js';
import { sendOTP as sendSMSOTP } from '../../services/smsService.js';
import * as cloudinaryService from '../../services/cloudinaryService.js';
import { SP_USER_ROLES, SP_WORKER_STATUS } from '../../constants.js';
import { validationResult } from 'express-validator';

const sendOTP_handler = async (req, res) => { try { const errors = validationResult(req); if (!errors.isEmpty()) return res.status(400).json({ success: false, message: 'Validation failed', errors: errors.array() }); const { phone } = req.body; const allowed = await checkRateLimit(phone); if (!allowed) return res.status(429).json({ success: false, message: 'Too many OTP requests.' }); const otp = generateOTP(); const otpHash = hashOTP(otp); await storeOTP(phone, otpHash); await sendSMSOTP(phone, otp); if (process.env.NODE_ENV === 'development' || process.env.USE_DEFAULT_OTP === 'true') console.log(`[DEV] Worker OTP for ${phone}: ${otp}`); res.status(200).json({ success: true, message: 'OTP sent successfully', token: 'verification-pending' }); } catch (error) { res.status(500).json({ success: false, message: 'Failed to send OTP.' }); } };

const verifyLogin = async (req, res) => { try { const { phone, otp } = req.body; const verification = await verifyOTP(phone, otp); if (!verification.success) return res.status(400).json({ success: false, message: verification.message }); const worker = await SpWorker.findOne({ phone }); if (worker) { if (!worker.isActive) return res.status(403).json({ success: false, message: 'Account deactivated.' }); const loginSessionId = Date.now().toString(); await SpWorker.findByIdAndUpdate(worker._id, { loginSessionId, $set: { fcmTokens: [], fcmTokenMobile: [] } }); const tokens = generateTokenPair({ userId: worker._id, role: SP_USER_ROLES.WORKER, loginSessionId }); return res.status(200).json({ success: true, isNewUser: false, message: 'Login successful', worker: { id: worker._id, name: worker.name, email: worker.email, phone: worker.phone, status: worker.status, serviceCategories: worker.serviceCategories || [] }, ...tokens }); } else { const verificationToken = generateVerificationToken(phone); return res.status(200).json({ success: true, isNewUser: true, message: 'OTP verified. Please complete registration.', verificationToken }); } } catch (error) { res.status(500).json({ success: false, message: 'Verification failed.' }); } };

const register = async (req, res) => { try { const errors = validationResult(req); if (!errors.isEmpty()) return res.status(400).json({ success: false, message: 'Validation failed', errors: errors.array() }); const { name, email, verificationToken, aadharNumber, aadharDocument, aadharBackDocument } = req.body; let phone = req.body.phone; if (verificationToken) { const verifiedPhone = verifyVerificationToken(verificationToken); if (!verifiedPhone) return res.status(400).json({ success: false, message: 'Invalid verification session.' }); phone = verifiedPhone; } else { if (!req.body.otp) return res.status(400).json({ success: false, message: 'Verification required.' }); const ver = await verifyOTP(phone, req.body.otp); if (!ver.success) return res.status(400).json({ success: false, message: ver.message }); } const existing = await SpWorker.findOne({ $or: [{ phone }, { email }] }); if (existing) return res.status(400).json({ success: false, message: 'Worker already exists.' }); let aadharUrl = aadharDocument || null; if (aadharUrl && aadharUrl.startsWith('data:')) { const r = await cloudinaryService.uploadFile(aadharUrl, { folder: 'workers/documents' }); if (r.success) aadharUrl = r.url; } const worker = await SpWorker.create({ name, email, phone, isPhoneVerified: true, aadhar: { number: req.body.aadhar || aadharNumber, document: aadharUrl }, status: SP_WORKER_STATUS.OFFLINE }); const loginSessionId = Date.now().toString(); await SpWorker.findByIdAndUpdate(worker._id, { loginSessionId }); const tokens = generateTokenPair({ userId: worker._id, role: SP_USER_ROLES.WORKER, loginSessionId }); res.status(201).json({ success: true, message: 'Registration successful', worker: { id: worker._id, name: worker.name, phone: worker.phone, status: worker.status }, ...tokens }); } catch (error) { res.status(500).json({ success: false, message: 'Registration failed.' }); } };

const login = async (req, res) => { try { const { phone, otp } = req.body; const verification = await verifyOTP(phone, otp); if (!verification.success) return res.status(400).json({ success: false, message: verification.message }); const worker = await SpWorker.findOne({ phone }); if (!worker) return res.status(404).json({ success: false, message: 'Worker not found.' }); if (!worker.isActive) return res.status(403).json({ success: false, message: 'Account deactivated.' }); const loginSessionId = Date.now().toString(); await SpWorker.findByIdAndUpdate(worker._id, { loginSessionId, $set: { fcmTokens: [], fcmTokenMobile: [] } }); const tokens = generateTokenPair({ userId: worker._id, role: SP_USER_ROLES.WORKER, loginSessionId }); res.status(200).json({ success: true, message: 'Login successful', worker: { id: worker._id, name: worker.name, phone: worker.phone, status: worker.status }, ...tokens }); } catch (error) { res.status(500).json({ success: false, message: 'Login failed' }); } };

const logout = async (req, res) => { try { const { platform = 'web' } = req.body; if (req.user && req.user.id) { const updateQuery = platform === 'mobile' ? { $set: { fcmTokenMobile: [], loginSessionId: null } } : { $set: { fcmTokens: [], loginSessionId: null } }; await SpWorker.findByIdAndUpdate(req.user.id, updateQuery); } res.status(200).json({ success: true, message: 'Logged out successfully' }); } catch (error) { res.status(500).json({ success: false, message: 'Logout failed' }); } };

const refreshToken = async (req, res) => { try { const { refreshToken } = req.body; if (!refreshToken) return res.status(400).json({ success: false, message: 'Refresh token is required' }); const decoded = verifyRefreshToken(refreshToken); if (!decoded) return res.status(401).json({ success: false, message: 'Invalid or expired refresh token' }); const worker = await SpWorker.findById(decoded.userId); if (!worker) return res.status(404).json({ success: false, message: 'Worker not found' }); if (!worker.isActive) return res.status(403).json({ success: false, message: 'Account not active' }); if (decoded.loginSessionId !== worker.loginSessionId) return res.status(401).json({ success: false, message: 'LoggedIn on another device.' }); const tokens = generateTokenPair({ userId: worker._id, role: SP_USER_ROLES.WORKER, loginSessionId: worker.loginSessionId }); res.status(200).json({ success: true, message: 'Token refreshed', ...tokens }); } catch (error) { res.status(500).json({ success: false, message: 'Failed to refresh token' }); } };

export { sendOTP_handler as sendOTP, verifyLogin, register, login, logout, refreshToken };
